credentials:
  system:
    domainCredentials:
      - credentials:
          - basicSSHUserPrivateKey:
              id: "buddywood-github"
              privateKeySource:
                directEntry:
                  privateKey: '''
                  -----BEGIN RSA PRIVATE KEY-----
MIIJKgIBAAKCAgEAoTOHb2tjvAxMI1IjtXAbRwqBf1I+xEDCWcSPMwfO4cKOJvph
veVsht0tJuEz+myP+ypHjKztoJQLpipcmkKCM7GSwUPzslcxulFGBSux9BxwhnNp
8JeNPnXpAZSx8RvuHbF50N7+3cq3idnq2VgUovmKl/UiOFrB6K7o0l+TBntlkAX5
1TuAtD0BBMkKgncIjFvSffvLJxtjVU7DZjvDOBId5tYvpYqTCakXJT/Y0t4HvTtc
KNTrjNUDe8A3ZGNFMIL0e/0QjyvyW0zpRq+1OmeZpK/K4DunJNT9sCxdtTXbc9t9
um/cRqw+6oj3KKlyrEO3KC3y+aC9YQesIC4fge7zIUL5XEoBLYNSztncmc2ydUEu
/LE1wfYlIzQs2xgMX8et1c/VHOahUd5LfTNunCI17aYU+Q2JUX9kXlb8JXQNf9Nq
lbOBhmUpQUeeJraUOsJbxH7cbo4VylN++/AY9S+sLL4+7ugRn4WSR3jSN3vWhbVb
RP/3JsfSmlRzBi8Bl/ZK6dVkXWpDb1znzib0MC69bY5pqhwDOjW79rGr/2uoTU0P
nEl6t2284rDzh03/eLJMVBZLs0Zo1IPjFSyQV28cr7X/PEDyn5nCusOfOISky3Bi
TLgKTQBiI96s/bf6LM0Z5GV83myW69f20TAsxzTO+8lSy/ETGakrB/MJbI0CAwEA
AQKCAgEAk+3Ckne9HXs3f45IIJ9RGN9GOP3Thatb7p7XPmAi9L/iTVily2q3LgfY
AH7XgS6Q7k89O5YRtrNFAWaMdi8kZqXE48Ak6XrksnMUy3fupPJYPLm69UNOJYx0
l7PJm1YjLHKKNCf/QK9fwIwO3QbcYTaYfZxBm++FVK72DuAP/vnMGN+zBX/GOyBk
R+zpzRHI8Wzt/BjNtASJImbWH4ImQtU1RXk2XjaNemcGS3OM2O1RstC/YOULh8CO
osigzGngu4ThMMrpoEkW7bvlsq1ZpNAfiaaciSuU1dLzPvFnyPw0d9xrQ2SVgvFc
B0RLc7AUAItfj+qit3tPbrRou1s4I0KOGLabtjxVG2p5FwpO+Wny9FBa2xBk6Nlt
x0PYobhdCbPdEbFRSFds0jefxlsyOMgJ5j9ZQcsUbpOtxmOKxbTXC0M3tXR0h51D
VXAWn6siPI+KLVHwpaIQUTf9KhHciY1RFdyG6Xo+vYPSRfhO0E94F+m0yRNWq75f
xravMMt3gBCKoNLWNcTIgS1mBIzDfkbWKDST4VPqTWm0wRDjPHE1obTzCyy2Tzym
u4UHVK77L8V9fesd23Od3WJybZ4rfyk9xwt5C54Rgiv1iQDBgYYldlTbG1/58n9P
imhKrVJG3xqGOD0jSrXCTotxKETo50esrAC77cp9coOMQg/5GW0CggEBANFfLUl7
QzM8AMxbb14qIOziyX7ZAlt3Jut5rjzZSlomw0QK4y1gCI2zh1eMQAXEls1Q9SN8
oulMK+w4tWRCNHy1azMwgpK5nfGCcQx22tBXiuuVi8uoVespgicN1nxVysCGw6MJ
aj3M2sXOlwmiEgbNZQAXjvxKa/6bIi/mQl6vuBX1Qt4dbuwXG4LBQkY8zxCbYR0P
x5m4mefNc46Sy8RU8RCaSzuznsG8tTicDXBzH/FlRF9hmCzkk8tnOGFXs+GRKwsM
Io9Y8XO+aTBZBW8fdijHdFAmdgvsry9sHFXRG39uSgL8H4waqnobjieteRhn8LgJ
xQoq/JA3Cq22f18CggEBAMUaBzy7t9dNSWxmcbViJm5hy/wpcncmpV3ta2G3yT+/
Wip/qoveCZimgrOnpPXQczh0/mVjUJxYCrXqi6TYgd+Iibm/+3Oof2++hSEDWII1
ytkzo73ovgnwTrpBXoeZn4tK8NlC88WZiFLHF1YxoRc77e5htn/EHHNg+/LKNTIZ
L68vJ0SvMi2X5doTzwyDUOGirSDyVm1iZN1FFdLArK5yW5C9w7ZcXohLwhnchx12
a/K9DPZNKQaEjP+sTqphbu7i+orPuQzLZr2xCYWBiUdaiNs5XePinshrUU/6/eyw
Pq2A43HTG8LmyAO0tMrQMH6wZ2jr9y4qnqhV49crV5MCggEBALTx+5KY67/YqJv0
nbAU2rW/XgK5i7b+p+00EShXZlG5VGJ2wlVRvLKyKFK6TA5wEyBISkOsEKNtiDwz
2lhWe0QYChiIYSBrOJwjbo4mHf+W2OG3McUFq5N8IRadd/OmtX5kOamqll3osF3p
qFDT955XXmWQ9qsFqoW1Dvu0lUF9vauEdpC9gUKaydTcLunC3fVtQ6W5IHiyuJhD
0A20wlPgUSJXJpPnLVokO74758V6SW33ZfrEvp51wWE1yN0fzb8xFbELgMbASJQO
SJxXI0IhP54ImnY2dyjhGZnzZh2ohYpBB8fCm4Ua+qBjNh0GaDR2h+yVzOt3sST1
3M26fiMCggEAMJkVVb03PAfbZbXwrXdw4GCOqjMR/RzzQzCJ/IMTRPuKYNYvl+L8
XL4ZlfBs9Qsbjb0TCK6vLo1qvqYBHnkftJz20Gzss/zExymjq5smlJxs0pcv9WBQ
kyTEVJpPk4GmW/LzZa5jasJLYZWjRGZiQNdO+Crxk5koJq6wEJIZAaxCHKC0vvOv
nJxKWTXvJDewlqHErE30T24mToR9OAS3zx91Qj/35Jvr1xFO34+HZRVQ0n4YlxY5
WlkOZu/2SX5SmuYuPlGvX987CuR+44Mn9Qb2nY8MfmbfHa2QU/cf6t8d5SvVaLhT
rP+4K2m/9g3VFzepl64uuRxbGEhtMB2IrwKCAQEAkEKl+0Sq1MXQ/VmPMwoxOzUv
MWdlw+U3y3W1WqEZxtnJVcizHrvaNDvq3kEitpx415deP4ZdC2FxRXP3RC88tGTE
m3EKyY3JwWa/H/tY1Ljxf630G652/huGYI/fsE0NZvvGjeDRiJHkTdkTHUUBJhUN
ebRV+aKDK3PtDf3lQjELtt19Vogl+AbhZVk8hTnJyd5z6Y2nPjvHL4oLRRQqRNll
UpMDuHznC6+C+BOBzC/GV5ypQyDJAKwYECz/fuKu9X+5jFN6Kq/++N9s3nlTab65
YRvcalpEXaKx1EHiXj6tO/RInztLKNE7GoYNwzOPU44Z4akuOqNHwcssdEcVig==
-----END RSA PRIVATE KEY-----
'''
              scope: GLOBAL
              username: "buddywood"
jenkins:
  agentProtocols:
    - "JNLP4-connect"
    - "Ping"
  authorizationStrategy: "loggedInUsersCanDoAnything"
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
  disableRememberMe: false
  labelAtoms:
    - name: "built-in"
  markupFormatter: "plainText"
  mode: NORMAL
  myViewsTabBar: "standard"
  numExecutors: 2
  primaryView:
    all:
      name: "all"
  projectNamingStrategy: "standard"
  quietPeriod: 5
  remotingSecurity:
    enabled: true
  scmCheckoutRetryCount: 0
  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
        - id: "admin"
          password: "Ave-dawg"
          name: "admin"
          properties:
            - "apiToken"
            - "mailer"
            - "favorite"
            - "myView"
            - preferredProvider:
                providerId: "default"
            - "timezone"
            - "experimentalFlags"
  slaveAgentPort: 50000
  systemMessage: "debug-casc"
  updateCenter:
    sites:
      - id: "default"
        url: "https://updates.jenkins.io/update-center.json"
  views:
    - all:
        name: "all"
  viewsTabBar: "standard"
globalCredentialsConfiguration:
  configuration:
    providerFilter: "none"
    typeFilter: "none"
security:
  apiToken:
    creationOfLegacyTokenEnabled: false
    tokenGenerationOnCreationEnabled: false
    usageStatisticsEnabled: true
  gitHooks:
    allowedOnAgents: false
    allowedOnController: false
  gitHostKeyVerificationConfiguration:
    sshHostKeyVerificationStrategy: "acceptFirstConnectionStrategy"
  globalJobDslSecurityConfiguration:
    useScriptSecurity: false
  sSHD:
    port: -1
unclassified:
  bitbucketEndpointConfiguration:
    endpoints:
      - bitbucketCloudEndpoint:
          enableCache: false
          manageHooks: false
          repositoriesCacheDuration: 0
          teamCacheDuration: 0
  buildDiscarders:
    configuredBuildDiscarders:
      - "jobBuildDiscarder"
  buildStepOperation:
    enabled: false
  email-ext:
    adminRequiredForTemplateTesting: false
    allowUnregisteredEnabled: false
    charset: "UTF-8"
    debugMode: false
    defaultBody: |-
      $PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS:

      Check console output at $BUILD_URL to view the results.
    defaultSubject: "$PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS!"
    defaultTriggerIds:
      - "hudson.plugins.emailext.plugins.trigger.FailureTrigger"
    maxAttachmentSize: -1
    maxAttachmentSizeMb: -1
    precedenceBulk: false
    watchingEnabled: false
  enrichedSummaryConfig:
    enrichedSummaryEnabled: false
    httpClientDelayBetweenRetriesInSeconds: 1
    httpClientMaxRetries: 3
    httpClientTimeoutInSeconds: 1
  fingerprints:
    fingerprintCleanupDisabled: false
    storage: "file"
  gitHubConfiguration:
    apiRateLimitChecker: ThrottleForNormalize
  gitHubPluginConfig:
    hookUrl: "http://localhost:8080/github-webhook/"
  globalTimeOutConfiguration:
    operations:
      - "abortOperation"
    overwriteable: false
  injectionConfig:
    allowUntrusted: false
    checkForBuildAgentErrors: false
    enabled: false
    enforceUrl: false
    injectCcudExtension: false
    injectMavenExtension: false
  junitTestResultStorage:
    storage: "file"
  location:
    adminAddress: "address not configured yet <nobody@nowhere>"
  mailer:
    charset: "UTF-8"
    useSsl: false
    useTls: false
  mavenModuleSet:
    localRepository: "default"
  pollSCM:
    pollingThreadCount: 10
  scmGit:
    addGitTagAction: false
    allowSecondFetch: false
    createAccountBasedOnEmail: false
    disableGitToolChooser: false
    hideCredentials: false
    showEntireCommitSummaryInChanges: false
    useExistingAccountWithSameEmail: false
  timestamper:
    allPipelines: false
    elapsedTimeFormat: "'<b>'HH:mm:ss.S'</b> '"
    systemTimeFormat: "'<b>'HH:mm:ss'</b> '"
tool:
  git:
    installations:
      - home: "git"
        name: "Default"
  mavenGlobalConfig:
    globalSettingsProvider: "standard"
    settingsProvider: "standard"
